# **Numpy**

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [4]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
arr[-1][1]

np.int64(8)

In [6]:
# Reassigning
arr[0]=[9,0,0]
arr

array([[9, 0, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# Slicing
arr[0][0:2]

array([9, 0])

In [9]:
arr1=np.array([8,9,0,77])
arr2=np.array([1,2,3,0])
sum=arr1+arr2
sum

array([ 9, 11,  3, 77])