# **Numpy**

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [6]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
arr[-1][1]

np.int64(8)

In [8]:
# Reassigning
arr[0]=[9,0,0]
arr

array([[9, 0, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# Slicing
arr[0][0:2]

array([9, 0])

In [10]:
arr1=np.array([8,9,0,77])
arr2=np.array([1,2,3,0])
sum=arr1+arr2
sum

array([ 9, 11,  3, 77])

In [11]:
pro=arr1*arr2
pro

array([ 8, 18,  0,  0])

In [13]:
div=arr1/arr2
div

C:\Users\IT PARK\AppData\Local\Temp\ipykernel_6296\3646284451.py:1: RuntimeWarning: divide by zero encountered in divide
  div=arr1/arr2


array([8. , 4.5, 0. , inf])