In [1]:
# !pip install numpy

  Using cached numpy-2.0.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
Using cached numpy-2.0.1-cp312-cp312-win_amd64.whl (16.3 MB)


In [2]:
import numpy as np

In [5]:
## Creating arrays
##1D Array
arr1=np.array([1,2,3,4])
print(arr1)

[1 2 3 4]


In [6]:
print(type(arr1))

<class 'numpy.ndarray'>


In [7]:
print(arr1.shape)

(4,)


In [17]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [18]:
print(arr2)
print(arr2.shape)

[1 2 3 4 5]
(5,)


In [19]:
## 2D arrays

arr3=np.array([[1,2,3],[4,5,6]])
print(arr3)
print(arr3.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [23]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [25]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
## Identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
## Attributes of numpy array

arr=np.array([[1,2,3,4],[5,6,7,8]])
print("Array:\n",arr)
print("Shape:",arr.shape)
print("Number of dimention",arr.ndim)
print("Size:",arr.size)
print("DataTypes:",arr.dtype)
print("Item size:",arr.itemsize)

Array:
 [[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4)
Number of dimention 2
Size: 8
DataTypes: int64
Item size: 8


In [37]:
## Numpy vectorized operation

arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

print("Addition: ",arr1+arr2)
print("Substraction:",arr1-arr2)
print("Multiplication: ",arr1*arr2)
print("Division:",arr1/arr2)

Addition:  [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [38]:
## UNiversal function
arr=np.array([2,3,4,5,6])

#square
print(np.sqrt(arr))

#Exponent
print(np.exp(arr))

#Sine
print(np.sin(arr))

# Log
print(np.log(arr))


[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [43]:
## Slicing operations

arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [46]:
arr[0][0]

np.int64(1)

In [52]:
arr[1:,1:3]

array([[ 7,  8],
       [12, 13]])

In [56]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [58]:
arr[1:]=100
print(arr)

[[  1   2   3   4   5]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [61]:
### Statistical concepts
data=np.array([1,2,3,4,5])
mean=np.mean(data)
print("Mean: ",mean)

std_dev=np.std(data)

#Normalization
normalized_data=(data-mean)/std_dev
print(normalized_data)

Mean:  3.0
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [63]:
## Logical operation
data=np.array([23,2,32,5,2,6,4,3,1,11,23,21])
data[data>3]

array([23, 32,  5,  6,  4, 11, 23, 21])

In [68]:
data[(data>=5) & (data<=50)]

array([23, 32,  5,  6, 11, 23, 21])